### ISSUE TITLE
[BUG] Fixing register page UI 

### ISSUE THREAD

**Issue by raghavawasthi24** [Nishitbaria/OpenGrame#10]
### Description

Currently, register page UI overflows at the bottom. I can fix it by making left side scrollbar only and right side fixed. 

### Screenshots

![Screenshot (219)](https://github.com/Nishitbaria/OpenGrame/assets/113261155/1be66c7c-e7bc-461d-8c3c-1f2c491c6977)

**Comment by Nishitbaria** [comment]
Hey @raghavawasthi24 You can start working on the issue 
Happy hacking ✨

**Comment by raghavawasthi24** [comment]
Thanks

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by raghavawasthi24** [comment]
@Nishitbaria can you make it level 2?
