### ISSUE TITLE
Added the search functionality on explore page

### ISSUE THREAD

**Issue by SrinivasDevolper** [Nishitbaria/OpenGrame#104]
### Description

**Actual behavior:**
When a user searches on a search page the search should be responsive to the user but the search functionality is not working well.

**Expected behavior:**
The search bar shows good results after fixing this bug on Explore Page

I am GSSOC24 Contributor
Please assign this issue, I would like to work on this issue

### Screenshots

https://github.com/Nishitbaria/OpenGrame/assets/121508628/b202781e-acea-4e89-8c06-4882bbfa7fd9

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by SrinivasDevolper** [comment]
Thanks for assigned this issue

**Comment by Yash-Ainapure** [comment]
@Nishitbaria ,
Can you assign me this issue,as the assigned used isn't active on it
