### ISSUE TITLE
[OTHER] Grammatical Error

### ISSUE THREAD

**Issue by Unalia09** [Nishitbaria/OpenGrame#105]
### What would you like to share or ask?

![image](https://github.com/Nishitbaria/OpenGrame/assets/147930477/59c3595d-8459-4fc0-8224-c3f13dc99e60)
Just a small grammatical error it should be **"don't"** instead of "dont".

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
Hey @Unalia09  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨
