### ISSUE TITLE
[Feature] Adding Legal Pages

### ISSUE THREAD

**Issue by Hemashree21** [Nishitbaria/OpenGrame#108]
### Description

I want to work on adding these 3 Legal Pages to the website so that users will know how you will interact with the website. It can be added in the settings menu.
@Nishitbaria what do you think?

### Screenshots

![image](https://github.com/Nishitbaria/OpenGrame/assets/138188163/9b31c492-2acb-4c42-b9e9-158aca03a2f6)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Hemashree21** [comment]
![image](https://github.com/Nishitbaria/OpenGrame/assets/138188163/15b55435-8de0-43e5-8ebd-be597a8abaa3)

@Nishitbaria whenever I try to login or signup its showing error, I followed all the steps for installation from the Readme file and also added .env file. It's showing 404 error. How can I resolve it?

**Comment by Nishitbaria** [comment]
> ![image](https://private-user-images.githubusercontent.com/138188163/333792247-15b55435-8de0-43e5-8ebd-be597a8abaa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MzQ5OTcsIm5iZiI6MTcxNjYzNDY5NywicGF0aCI6Ii8xMzgxODgxNjMvMzMzNzkyMjQ3LTE1YjU1NDM1LThkZTAtNDNlNS04ZWJkLWJlNTk3YThhYmFhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMDU4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWE5YTcxOGQ3MDU3OTY5ZWIxYzhiZTc2NjYzM2RiMGQ5NjJmYmZkZTkyZDZkYjljNzg3NzU5Nzg2MjU2NzA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tHz9oXRLIWdS49eHHBpyVweP60u7D98I_Ifa2Ip2KaA)
> 
> @Nishitbaria whenever I try to login or signup its showing error, I followed all the steps for installation from the Readme file and also added .env file. It's showing 404 error. How can I resolve it?

Hey You have to use your own api key to run project for the api key  you have to create project on appwrite and using cli and appwrite.json you have to deploy project backend on your appwrite account then project is run locally

**Comment by Hemashree21** [comment]
> > ![image](https://private-user-images.githubusercontent.com/138188163/333792247-15b55435-8de0-43e5-8ebd-be597a8abaa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MzQ5OTcsIm5iZiI6MTcxNjYzNDY5NywicGF0aCI6Ii8xMzgxODgxNjMvMzMzNzkyMjQ3LTE1YjU1NDM1LThkZTAtNDNlNS04ZWJkLWJlNTk3YThhYmFhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMDU4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWE5YTcxOGQ3MDU3OTY5ZWIxYzhiZTc2NjYzM2RiMGQ5NjJmYmZkZTkyZDZkYjljNzg3NzU5Nzg2MjU2NzA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tHz9oXRLIWdS49eHHBpyVweP60u7D98I_Ifa2Ip2KaA)
> > @Nishitbaria whenever I try to login or signup its showing error, I followed all the steps for installation from the Readme file and also added .env file. It's showing 404 error. How can I resolve it?
> 
> Hey You have to use your own api key to run project for the api key you have to create project on appwrite and using cli and appwrite.json you have to deploy project backend on your appwrite account then project is run locally

Ohh okay, thankyou

**Comment by Hemashree21** [comment]
@Nishitbaria I am not that familiar with appwrite and I am not able to make those changes. can you please assign the issue to someone else? I am extremely sorry for the inconvinience.

**Comment by Nishitbaria** [comment]
> @Nishitbaria I am not that familiar with appwrite and I am not able to make those changes. can you please assign the issue to someone else? I am extremely sorry for the inconvinience.

Take ref of this api keys : 

```
VITE_APPWRITE_PROJECT_ID="664b72c700235fef3e76"
VITE_APPWRITE_URL="https://cloud.appwrite.io/v1"
VITE_APPWRITE_STORAGE_ID="65478ceca6d8a49b3cf1"
VITE_APPWRITE_DATABASE_ID="3j22cy28uc3"
VITE_APPWRITE_SAVES_COLLECTION_ID="65479a44782ab930d6f3"
VITE_APPWRITE_USERS_COLLECTION_ID="65479b3f3ff36d0c3fa6"
VITE_APPWRITE_POSTS_COLLECTION_ID="65479a1224b7d12ccb6e"
VITE_APPWRITE_STORIES_DATA_COLLECTION_ID="664c1dba0005c3bb2eae"
```

**Comment by Hemashree21** [comment]
@Nishitbaria I completed it and created a PR, can you please add gssoc label and level label for this isuue and the PR? Thankyou!
