### ISSUE TITLE
Request for Proper Credit to Original Tutorial Creator

### ISSUE THREAD

**Issue by heyhimansh** [Nishitbaria/OpenGrame#113]
hey @Nishitbaria ,

I hope you are doing well. I recently noticed your project and observed that it bears a striking resemblance to a tutorial from JavaScript Mastery. It seems that the code has been directly **copied without acknowledging the original source.**

To honor the effort and creativity of JavaScript Mastery, I kindly ask that you give proper credit to them. This can be done by mentioning the original tutorial in your project documentation. Here is the link to the tutorial for your reference: [JavaScript Mastery Tutorial](https://www.youtube.com/watch?v=_W3R2VwRyF4).    @adrianhajdin

Acknowledging the original creator not only shows respect for their work but also fosters integrity and transparency within our community. Thank you for your understanding and cooperation. 

Thank you 
Himanshu

**Comment by Nishitbaria** [comment]
> hey @Nishitbaria ,
> 
> I hope you are doing well. I recently noticed your project and observed that it bears a striking resemblance to a tutorial from JavaScript Mastery. It seems that the code has been directly **copied without acknowledging the original source.**
> 
> To honor the effort and creativity of JavaScript Mastery, I kindly ask that you give proper credit to them. This can be done by mentioning the original tutorial in your project documentation. Here is the link to the tutorial for your reference: [JavaScript Mastery Tutorial](https://www.youtube.com/watch?v=_W3R2VwRyF4).    @adrianhajdin
> 
> 
> Acknowledging the original creator not only shows respect for their work but also fosters integrity and transparency within our community. Thank you for your understanding and cooperation. 
> 
> Thank you 
> Himanshu
> 

Actually I didn't think we need to do that because there is so many things and customisation done by me and maintaining by me JSM Never said that mention him in the video
