### ISSUE TITLE
[Feature] Preloader

### ISSUE THREAD

**Issue by Jagpreet153** [Nishitbaria/OpenGrame#114]
### Description

I would like to add  a preloader to your site to make it more user friendly . The preloader would be consisting of small animation in JSON format which would render until the page is being loaded .

### Screenshots

https://github.com/Nishitbaria/OpenGrame/assets/119691733/ab0e606b-ecb3-41e8-b335-08d1bc27ed34

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
Hey @Jagpreet153  Loading State is already there
