### ISSUE TITLE
[Feature] Addition of user authntication

### ISSUE THREAD

**Issue by khy05dua** [Nishitbaria/OpenGrame#115]
### Description

Addition of security features and user authentication via google and email address if user forgets its password it can be sent on the email address and addition of two factor authentication ,i can work on that please assign me this task i have worked earlier on security features as well.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Heena31** [comment]
Kindly assign this issue to me @Nishitbaria.

**Comment by khy05dua** [comment]
@Nishitbaria  thankyou for assigning. Will provide you the work soon

**Comment by Heena31** [comment]
@Nishitbaria As I can see this is high priority task right now if it is okay with @khy05dua I would like to work on this issue asap

**Comment by khy05dua** [comment]
@Heena31 i am currently working on the project , will be sharing changes soon
