### ISSUE TITLE
Give proper credit in the official webpage to JavaScript Mastery

### ISSUE THREAD

**Issue by ElvinPero** [Nishitbaria/OpenGrame#116]
### What would you like to share or ask?

Dear Nishitbaria,

I have noticed that this project is straight up cloned from JavaScript Mastery youtube channel which disincentivises the original creator. While getting inspired from a project is no crime, there is a line between stealing credit from the original creator and taking inspiration.
I see that you are actively maintaining the project which definitely is a great thing but the original source code is more than 90%.
I also noticed that a similar PR earlier was closed by you without taking any action. Giving appropriate credits will only make you a better programmar and a humble human being. 

Do acknowledge my request.

Elvin

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by ritviz344** [comment]
I support this request. Utilizing community projects without proper credit is unprofessional and disrespectful to the original creators. It shows a lack of integrity and appreciation for the hard work put in by others.   @Nishitbaria

**Comment by Nishitbaria** [comment]
> > Hey @ritviz344 I appreciate you can do that but i will not provide any gssoc label for this issue because you are not doing a meaningful contribution
> 
> Hey @Nishitbaria I am not a GSSOC contributer this year. May be you can add the credits yourself "Inspired from JavaScript Mastery and pushing new boundaries to the project" on the homepage. I will look in future if thats implemented by you.

Done with that
