### ISSUE TITLE
[Feature] Add footer in the navbar.

### ISSUE THREAD

**Issue by sristy17** [Nishitbaria/OpenGrame#118]
### Description

Can add footer in the navbar section, including copywright, etc.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
Hey @sristy17 We don't need a footer in my project
