### ISSUE TITLE
[BUG] <Enhance loading of webpages>

### ISSUE THREAD

**Issue by AkashkumarChoudhary** [Nishitbaria/OpenGrame#12]
### Description

I can fix the bug of slow loading but apply syntax of lazyLoading to this website. Please assign me this issue.

### Screenshots

![Screenshot 2024-05-10 194818](https://github.com/Nishitbaria/OpenGrame/assets/109291117/b9ea870a-d561-4724-868a-6fe9f18c77d4)

### Any additional information?

I can  also use suspense for the improvement

**Comment by Nishitbaria** [comment]
Hey @AkashkumarChoudhary  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨
