### ISSUE TITLE
[Feature] our story icon , where user can click and see there own story 

### ISSUE THREAD

**Issue by ayushpatel1248** [Nishitbaria/OpenGrame#121]
### Description

- there is no icon where user can see there own story which is uploaded by them

- creating own story icon like instagram where user can click can se there own story uploaded by them
- icon like others story 
- can you assign me this under gssoc label

### Screenshots

<img width="1440" alt="Screenshot 2024-06-13 at 4 16 56 PM" src="https://github.com/Nishitbaria/OpenGrame/assets/127100604/b0718e22-4d54-4528-8379-8b803ee6ea5f">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by ayushpatel1248** [comment]
@Nishitbaria  can you please check it out

**Comment by ayushpatel1248** [comment]
@Nishitbaria can you give me gssoc level label

**Comment by Nishitbaria** [comment]
> @Nishitbaria can you give me gssoc level label

Hey first start working on the issue then i will decied which level i have to give @ayushpatel1248

**Comment by ayushpatel1248** [comment]
hey @Nishitbaria  after analysing complete code i got know that in our deployed website we cant see our story icon because whatever database id you are using in deployed application in that stories database i think mystoryid is not present there for that icon is not displayed on the frontend but as you have provided me the storiesid when i run it in the local server it shows the my story icon.
so my suggestion is to include currentuser id always in the database so that my story icon can always visible wheather my story is uploaded or not .
this are the ss
<img width="1440" alt="Screenshot 2024-06-25 at 4 50 52 PM" src="https://github.com/Nishitbaria/OpenGrame/assets/127100604/8302b47f-3410-48b0-8acd-c61f137aa3e2">
<img width="1440" alt="Screenshot 2024-06-25 at 4 50 55 PM" src="https://github.com/Nishitbaria/OpenGrame/assets/127100604/81ad95d4-07ae-4487-91c8-90ac37033c49">
<img width="1440" alt="Screenshot 2024-06-25 at 4 51 25 PM" src="https://github.com/Nishitbaria/OpenGrame/assets/127100604/e32f9d9b-09b7-4f5c-b977-9eb4ca1dddaa">
<img width="449" alt="Screenshot 2024-06-25 at 4 51 35 PM" src="https://github.com/Nishitbaria/OpenGrame/assets/127100604/5c59c95e-3dfd-48b3-bc9b-85994e67613c">
