### ISSUE TITLE
[DOCS] Documantation for docker

### ISSUE THREAD

**Issue by Dhruv-Pattel** [Nishitbaria/OpenGrame#123]
### Issue Description

current CONTRIBUTING.md file isn't beginner-friendly for working with docker.

### Screenshots or Examples (if applicable)

![dfadfafd](https://github.com/Nishitbaria/OpenGrame/assets/140754596/38f29f47-34c0-4f3a-b74b-2bc47b762e80)

### Proposed Solution (optional)
I can create clear documentation for running the Docker container, making it easy for beginners to understand.

### Checklist

- [X] I have checked the existing [issues](https://github.com/Nishitbaria/OpenGrame/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
Hey @Dhruv-Pattel  Please don't create multiple issue i have assign docker doc related issue please works on that
