### ISSUE TITLE
[DOCS] VITE_APPWRITE_STORIES_COLLECTION_ID is not provided in the example .env file which is required to load the stories data in local host 

### ISSUE THREAD

**Issue by ayushpatel1248** [Nishitbaria/OpenGrame#124]
### Issue Description

VITE_APPWRITE_STORIES_COLLECTION_ID is not provided in the example .env file which is required to load the stories data in local host 

this is essential to load the story data in local host 
that is why i am unable to add my story icon in my other issue raised 

### Screenshots or Examples (if applicable)

<img width="700" alt="Screenshot 2024-06-22 at 9 04 43 PM" src="https://github.com/Nishitbaria/OpenGrame/assets/127100604/510a03cf-db5b-4647-8382-22360026527c">
this is required 
<img width="565" alt="Screenshot 2024-06-22 at 9 05 02 PM" src="https://github.com/Nishitbaria/OpenGrame/assets/127100604/f736ef4e-e4ff-40d7-a3f1-6e8a1016d77f">
in this env we dont have this 

### Checklist

- [X] I have checked the existing [issues](https://github.com/Nishitbaria/OpenGrame/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by ayushpatel1248** [comment]
@Nishitbaria please look after this as i have to add another story icon in the another issue raised

**Comment by ayushpatel1248** [comment]
@Nishitbaria actually i didnt got the points for this issue although you have given the label level1  and also it is closed as completed please look after this

**Comment by Nishitbaria** [comment]
> @Nishitbaria actually i didnt got the points for this issue although you have given the label level1  and also it is closed as completed please look after this 

Actually I forgot to remove the labels

**Comment by ayushpatel1248** [comment]
> > @Nishitbaria actually i didnt got the points for this issue although you have given the label level1  and also it is closed as completed please look after this
> 
> Actually I forgot to remove the labels

@Nishitbaria  so now ill get points or not ?

**Comment by Nishitbaria** [comment]
> > > @Nishitbaria actually i didnt got the points for this issue although you have given the label level1  and also it is closed as completed please look after this
> > 
> > Actually I forgot to remove the labels
> 
> @Nishitbaria  so now ill get points or not ?

Not because according to guidline it's not meaningful contribution

**Comment by ayushpatel1248** [comment]
> > > > @Nishitbaria actually i didnt got the points for this issue although you have given the label level1  and also it is closed as completed please look after this
> > > 
> > > 
> > > Actually I forgot to remove the labels
> > 
> > 
> > @Nishitbaria  so now ill get points or not ?
> 
> Not because according to guidline it's not meaningful contribution

thanks for clearing the doubt 😊

**Comment by Nishitbaria** [comment]
> > > > > @Nishitbaria actually i didnt got the points for this issue although you have given the label level1  and also it is closed as completed please look after this
> > > > 
> > > > 
> > > > Actually I forgot to remove the labels
> > > 
> > > 
> > > @Nishitbaria  so now ill get points or not ?
> > 
> > Not because according to guidline it's not meaningful contribution
> 
> thanks for clearing the doubt 😊

If you facing any issue releted project then ping me in discord too I will try to help you 😉
