### ISSUE TITLE
[Feature] : Google/Linkedin Signup Functionality 

### ISSUE THREAD

**Issue by codercake** [Nishitbaria/OpenGrame#126]
### Description

Implementing Google and LinkedIn signup functionality involves integrating OAuth 2.0 protocols to allow users to authenticate using their existing Google or LinkedIn accounts. This integration simplifies the signup and login process, enhances security, and improves user convenience.

**Example Use Case:**
A user visits your application’s signup page and sees options to sign up with Google or LinkedIn. They click on the "Sign up with Google" button, are redirected to Google’s consent screen, approve the permissions, and are redirected back to OpenGrame. The backend verifies the token, fetches the user’s Google profile information, and either creates a new account or logs the user in.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Ashutosh-0506** [comment]
GIb
