### ISSUE TITLE
[Hover Effect] Hover effect on buttons on login and signup page

### ISSUE THREAD

**Issue by Atharva1723** [Nishitbaria/OpenGrame#13]
### Description

The current login page and signup page buttons don't have any buttons hover effect 
It would be visually appealing to users if we add hover effect on buttons 

### Screenshots

![Uploading issue_1.png…]()
![Uploading issue_2.png…]()

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by Nishitbaria** [comment]
please @agxmbedi  Don't spam and read Contribution.md
