### ISSUE TITLE
[Feature] Add footer to the website

### ISSUE THREAD

**Issue by PDBharadwaj** [Nishitbaria/OpenGrame#133]
### Description

I wanted to add footer to the bottom of the signup/login page.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
Its not require in the  website @PDBharadwaj
