### ISSUE TITLE
[BUG] Fixing Default Followers & Following.

### ISSUE THREAD

**Issue by prafulnigam** [Nishitbaria/OpenGrame#16]
### Description

It is displaying 20 followers & Following by default since start.

### Screenshots

![image](https://github.com/Nishitbaria/OpenGrame/assets/78497704/2a175bd7-c5f7-4a78-96e1-6825c2fa49c5)

**Comment by prafulnigam** [comment]
I am Praful Nigam. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by iamrudhresh** [comment]
Assign this issue to me under GSSoc'24
