### ISSUE TITLE
[LIke] adding the animation over like button 

### ISSUE THREAD

**Issue by agxmbedi** [Nishitbaria/OpenGrame#17]
### Description

adding and cool and eye catching animation over like button

### Screenshots

<img width="1440" alt="Screenshot 2024-05-10 at 10 58 03 PM" src="https://github.com/Nishitbaria/OpenGrame/assets/111156687/901c99c8-9ae0-4ca4-822e-120e327edc67">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by agxmbedi** [comment]
thank you sir

**Comment by Akshatakapare** [comment]
I want to add cool animation over the like button, please assign this task to me. I am contributing under GSSoC'24
