### ISSUE TITLE
[Feature] Invite Functionality for Others.

### ISSUE THREAD

**Issue by prafulnigam** [Nishitbaria/OpenGrame#19]
### Description

A link would be generated to invite others to the platform.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by prafulnigam** [comment]
I am Praful Nigam. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by prafulnigam** [comment]
Thank You !

**Comment by Sid-80** [comment]
@Nishitbaria I am willing to work on this issue, there is no response from 2 weeks

**Comment by Nishitbaria** [comment]
Hey @Sid-80  You can start working on this issue

**Comment by Sid-80** [comment]
@Nishitbaria Would you please assist where it should be located

**Comment by Nishitbaria** [comment]
> @Nishitbaria Would you please assist with where it should be located

You have to implement this feature from Scratch-It does not exist in the project

**Comment by Sid-80** [comment]
@Nishitbaria Have a look

DASHBOARD : 
![image](https://github.com/Nishitbaria/OpenGrame/assets/101277141/ed2460ed-25dd-4058-8753-30ad3ecff9df)

INVITE MODAL : 
![image](https://github.com/Nishitbaria/OpenGrame/assets/101277141/5f650a62-810b-4fec-a372-f0ba2072b86d)

**Comment by Sid-80** [comment]
@Nishitbaria We can integrate the resend for inviting user through mail

**Comment by Nishitbaria** [comment]
> @Nishitbaria We can integrate the resend for inviting user through mail

Yea we can do that too

**Comment by Sid-80** [comment]
@Nishitbaria If I want to share then which url should I use ?

**Comment by Nishitbaria** [comment]
> @Nishitbaria If I want to share then which url should I use ?

Use versel url to do that and add some metadata show it's showing inviting some one

**Comment by Sid-80** [comment]
@Nishitbaria Should I create separate issue for integrating email invitation using resend ?
