### ISSUE TITLE
[BUG] Error while Updating the Profile Picture.

### ISSUE THREAD

**Issue by prafulnigam** [Nishitbaria/OpenGrame#20]
### Description

One is Unable to change the profile, resulting in an error.

### Screenshots

![Screenshot 2024-05-10 230154](https://github.com/Nishitbaria/OpenGrame/assets/78497704/e5978beb-d53c-49eb-a7db-cb98e311616b)

**Comment by prafulnigam** [comment]
I am Praful Nigam. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by Nishitbaria** [comment]
Hey @prafulnigam  Currently I haven't implemented this feature We need to modify the user Schema in Appwrite

**Comment by prafulnigam** [comment]
okay, I'll look into it.

**Comment by Nishitbaria** [comment]
Hey @prafulnigam I am assigning this issue to you

you can start working on this issue 

Happy hacking
