### ISSUE TITLE
[Feature] Implementation of Follow request

### ISSUE THREAD

**Issue by krushn-a** [Nishitbaria/OpenGrame#21]
### Description

Currently the follow feature is not implemented and the follower number is also hard coded.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by krushn-a** [comment]
@Nishitbaria I want to work on this issue under GSSOC'24. Could you assign it to me.

**Comment by Nishitbaria** [comment]
You can start working on this issue @krushn-a 
Happy hacking ✨

**Comment by iamrudhresh** [comment]
Assign this issue to me under GSSoc'24

**Comment by krushn-a** [comment]
hi @Nishitbaria i was having some doubt whether we should the data for followers and following as new collection in appwrite or it should be stored in local storage

**Comment by krushn-a** [comment]
hi @Nishitbaria whether we have to make a new collection to store followers and following or are we can use local storage

**Comment by Nishitbaria** [comment]
> hi @Nishitbaria whether we have to make a new collection to store followers and following or are we can use local storage

Yes @krushn-a We have to add the following and followers' field in an existing collection called User

here : 

![image](https://github.com/Nishitbaria/OpenGrame/assets/85815172/70ff6811-6b16-48b3-89e0-268be6a81c20)


I have a dummy account with the same configuration Lets me know If you need otherwise you have to set on your appwrite  account

**Comment by krushn-a** [comment]
it will be helpful if you can provide me any dummy account

**Comment by Nishitbaria** [comment]
> it will be helpful if you can provide me a dummy account

use email and as password same: limamex886@godsigma.com

**Comment by Sid-80** [comment]
@Nishitbaria Hey I am willing to work on this issue!

**Comment by Sid-80** [comment]
@Nishitbaria I am willing to work on this issue

**Comment by Nishitbaria** [comment]
> @Nishitbaria I am willing to work on this issue

Hey can you please work on one issue ? 
I already assigned one issue
