### ISSUE TITLE
[BUG] : Image Path missing

### ISSUE THREAD

**Issue by sivaprasath2004** [Nishitbaria/OpenGrame#23]
### Description

In the `create` page image element has missing the `src` path.

### Screenshots

![Screenshot from 2024-05-11 08-15-43](https://github.com/Nishitbaria/OpenGrame/assets/121082414/e5a8d1dd-a2dd-4748-a495-6d5f4a2dfe5a)

### Any additional information?

The miss match of the `src` path change to the orginal path like that can be image will be displayed.

### What browser are you seeing the problem on?

- In the `chrome` browser can be seeing the error.

**Comment by Nishitbaria** [comment]
Hello @sivaprasath2004, I’ve noticed a bug on this route. Could you please fix it?

I’m assigning this issue to you

**Comment by sivaprasath2004** [comment]
@Nishitbaria Yes i will work

**Comment by Nishitbaria** [comment]
Closing this issue its completed
