### ISSUE TITLE
[Feature] Filter posts by popularity, relevance and latest

### ISSUE THREAD

**Issue by raghavawasthi24** [Nishitbaria/OpenGrame#24]
### Description

Filters will be added to sort the posts.
Users will have option like
 - relevance
 - popularity
 - latest

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
Hey I have already one issue so i am open this issue for other

**Comment by raghavawasthi24** [comment]
@Nishitbaria previous issue is not a big one. I can take this too.

**Comment by Nishitbaria** [comment]
> @Nishitbaria previous issue is not a big one. I can take this too.

then please complete that first

**Comment by Atharva1723** [comment]
Can I go on this ?

**Comment by raghavawasthi24** [comment]
can you give it level 3 because it would be working from scratch ?
