### ISSUE TITLE
[Feature] Adding Search functionality on people page

### ISSUE THREAD

**Issue by tuwid-Ashish** [Nishitbaria/OpenGrame#25]
### Description

Create a search bar in people page for users to Search other users .
### Proposed Approach:

**Appwrite Integration:** Utilize Appwrite's query filtering capabilities to filter the list of people based on the search criteria.

**Frontend Implementation:** Integrate the search bar component on the people page

**Error Handling:** Implement error handling for cases where the search query may not yield any results. Provide informative feedback to the user.

### Screenshots

![Screenshot 2024-05-11 120458](https://github.com/Nishitbaria/OpenGrame/assets/125805624/e1c22001-e104-4d20-ac95-3f668ceb107d)

**On a highlighted part I can add a search bar component  for users search queries.**

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by iamrudhresh** [comment]
Assign this issue to me under GSSoc'24

**Comment by Nishitbaria** [comment]
Hey @tuwid-Ashish I am Assising this issue to you 

And one point please Make search bar Look similar  like this :
