### ISSUE TITLE
Shimmer loading effect

### ISSUE THREAD

**Issue by siddxharth1** [Nishitbaria/OpenGrame#26]
Instead of this spinner we can introduce  the shimmer effect for loading which will improve the user experience

**Comment by Nishitbaria** [comment]
> Instead of this spinner we can introduce the shimmer effect for loading which will improve the user experience

can you show me that spinner @siddxharth1

**Comment by siddxharth1** [comment]
Sure, 
https://miro.medium.com/v2/resize:fit:828/format:webp/1*t9aoM75NQWqH7qi3boFuhQ.gif
Here you can see the example of implementation of shimmer effect which improve user experience.

**Comment by Nishitbaria** [comment]
Hey @siddxharth1 I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨
