### ISSUE TITLE
[BUG] : Home page always rendering from start.

### ISSUE THREAD

**Issue by Ech0Cipher** [Nishitbaria/OpenGrame#29]
## Description

The Home and Explore the page always rendaring from start.

## Steps to Reproduce

Longin into opengrame go on Home page scroll and click on any post after click on back you see ther home page render from start.

## Expected Behavior

when user click on post and get back the home page render from at particular position.Not from start.

https://github.com/Nishitbaria/OpenGrame/assets/166703372/dd0cd764-e693-4047-b94e-458073bf047a

### Note: 
Video quality is not good just just see the working.

### What browser are you seeing the problem on?

Chrome

**Comment by Ech0Cipher** [comment]
Hey @Nishitbaria i will fix this issue can you assign me this under gssoc'24.

**Comment by anniepauline** [comment]
Willing to work on this issue
