### ISSUE TITLE
[DOCS] Typo mistake

### ISSUE THREAD

**Issue by Sid-80** [Nishitbaria/OpenGrame#32]
### Issue Description

Typo error in technologies : Shadcn

### Screenshots or Examples (if applicable)

![image](https://github.com/Nishitbaria/OpenGrame/assets/101277141/dafc4db4-f98d-40c1-9fe8-f2a6d0eca469)

### Checklist

- [X] I have checked the existing [issues](https://github.com/Nishitbaria/OpenGrame/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Sid-80** [comment]
@Nishitbaria Is it correct ?

**Comment by Nishitbaria** [comment]
Hey @Sid-80  , your contribution won’t be needed right now. I’m working on a new readme file and will be replacing the entire content.
