### ISSUE TITLE
[Feature] Implement Share Profile Button”

### ISSUE THREAD

**Issue by Nishitbaria** [Nishitbaria/OpenGrame#34]
### Description

Make one button which helps to share the User Profile 

Acceptance Criteria:

- A ‘Share Profile’ button is visible on the user profile page.
- Clicking the button generates a unique URL that points to the user’s profile.
- The URL can be copied to the clipboard or shared directly through common social platforms.

### Screenshots

![image](https://github.com/Nishitbaria/OpenGrame/assets/85815172/55571277-1c2c-4af5-baa2-5b9cbc39c3d5)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Sid-80** [comment]
@Nishitbaria Please assign me this task!

**Comment by Sid-80** [comment]
@Nishitbaria There are two ways to perform it.
1. Self written code
2. External library

**Comment by Nishitbaria** [comment]
Option 1 is better choice

**Comment by Sid-80** [comment]
1. ![image](https://github.com/Nishitbaria/OpenGrame/assets/101277141/48075495-02ba-4414-8f6e-5124ae65b448)

Or

2. ![image](https://github.com/Nishitbaria/OpenGrame/assets/101277141/e4fb8a8d-73dc-41c4-85bf-e7fba121a7ba)

**Comment by Nishitbaria** [comment]
> @Nishitbaria Which looks perfect ?
> 
> 1. ![image](https://github.com/Nishitbaria/OpenGrame/assets/101277141/48075495-02ba-4414-8f6e-5124ae65b448)
> 
> Or
> 
> 2. ![image](https://github.com/Nishitbaria/OpenGrame/assets/101277141/e4fb8a8d-73dc-41c4-85bf-e7fba121a7ba)
> 
> 

2nd option looks great

**Comment by Nishitbaria** [comment]
Hey @Sid-80  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨

**Comment by Nishitbaria** [comment]
Hey @Sid-80  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨

**Comment by Sid-80** [comment]
Unassigned ?

**Comment by Nishitbaria** [comment]
Sorry I just testing Github Action that its work or not

**Comment by Sid-80** [comment]
It doesn't seems better ?

![image](https://github.com/Nishitbaria/OpenGrame/assets/101277141/e5c1ed5e-ba8e-46de-9ac1-8dbc35eff149)

Your views...

**Comment by Nishitbaria** [comment]
Yeah its compares to follow button It does not look aligned

**Comment by Sid-80** [comment]
![image](https://github.com/Nishitbaria/OpenGrame/assets/101277141/1bf978f7-399f-4cb1-b30d-b2f64108d51e)

1. Follow button to cover the width of share profile button 
2. Align the follow button to the center

**Comment by Nishitbaria** [comment]
Yea now its look better

**Comment by Sid-80** [comment]
In above acceptance criteria in 3rd one the url is getting copied to clipboard. I was not getting or part

**Comment by Nishitbaria** [comment]
> @Nishitbaria In above acceptance criteria in 3rd one the url is getting copied to clipboard. I was not getting or part. I think we should add a popover with different social media platform logos

Yups We can do this

**Comment by Sid-80** [comment]
Okey then I will give it a try!

**Comment by Sid-80** [comment]
![image](https://github.com/Nishitbaria/OpenGrame/assets/101277141/068c88a8-97fc-46bb-9a3e-8b5c797ba16d)

@Nishitbaria Ok?

**Comment by Nishitbaria** [comment]
> ![image](https://private-user-images.githubusercontent.com/101277141/329826987-068c88a8-97fc-46bb-9a3e-8b5c797ba16d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0OTEzNzksIm5iZiI6MTcxNTQ5MTA3OSwicGF0aCI6Ii8xMDEyNzcxNDEvMzI5ODI2OTg3LTA2OGM4OGE4LTk3ZmMtNDZiYi05YTNlLThiNWM3OTdiYTE2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQwNTE3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzU4MGVhN2Q3NTU4YjBlMjdjZmVmNmEzMTliNGZiNmJmMzRiMjJiYTFkYmZhOWRhOGZmMGRlOTY3NGIzZjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QvhBFv3dCU4VVgTyKSCaAvo1cH_1b1Rk9drgZTp6y3U)
> 
> @Nishitbaria Ok?

Take Ref Modal: Because we are using shadcn then please use this component for Dialog: [click](https://ui.shadcn.com/docs/components/dialog)

**Comment by Sid-80** [comment]
Sure!
@Nishitbaria Shall I just pass the social media links in it or something else?

**Comment by Nishitbaria** [comment]
> Sure! @Nishitbaria Shall I just pass the social media links in it or something else?

**I think we have to make this feature for a post that is good not for sharing profiles on social media**


see i want to make like this i hope you understand what i want to say

![image](https://github.com/Nishitbaria/OpenGrame/assets/85815172/a1661104-54ef-44ec-a501-7ccd7d67197a)

**Comment by Sid-80** [comment]
Yepp! Got it

**Comment by Sid-80** [comment]
We can keep this feature for both post as well as profile. What's your view ?

**Comment by Nishitbaria** [comment]
> We can keep this feature for both post as well as profile. What's your view ?

In user Profile its okay for share the post adding other social media option will be better
