### ISSUE TITLE
[Feature] : Logout Alerting screen

### ISSUE THREAD

**Issue by sivaprasath2004** [Nishitbaria/OpenGrame#36]
### Description

If the user can `logout` option click that is show nothing automatically can logout.
- If i will to implement new feature to confirmation `Conform` or `cancel` this can be more usable.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by avayyyyyyy** [comment]
Hey! @Nishitbaria I have fixed this issue kindly assign me this so I can create a pull request.

Thank you
