### ISSUE TITLE
[Feature] Add Signup and Login with Google using Appwrite

### ISSUE THREAD

**Issue by Nishitbaria** [Nishitbaria/OpenGrame#37]
### Description

I want to signup and log in with Google using Appwrite 

- user able to sign up or log in using Google
- for this, we have configuration using appwrite 
- data must be save in the User collection 

### Screenshots

![image](https://github.com/Nishitbaria/OpenGrame/assets/85815172/1f392edc-bbd0-44c7-990e-58f79d5d713d)

Figma file ref : https://www.figma.com/file/y7OzDDuGVslwr9rOYDQ7i2/OpenGrame?type=design&node-id=0%3A1&mode=design&t=aMzewIEoN9dd3iFD-1

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by DhruvPandey1** [comment]
Hello @Nishitbaria !
Please assign this issue to me I have good experience with working on  appwrite and adding google login to it
So, Can you assign this issue to me.

**Comment by Nishitbaria** [comment]
Hey @DhruvPandey1  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨

**Comment by DhruvPandey1** [comment]
Hello @Nishitbaria ! 
I have resolved the and made a PR please review and merge it Under GSSOC'24 level3

**Comment by codercake** [comment]
Hello, PA! @Nishitbaria 
Could you assign me this issue? Would be happy to contribute!
