### ISSUE TITLE
[Feature] Feature Request: Display Top Creators Based on Likes and Posts in Left Sidebar

### ISSUE THREAD

**Issue by Nishitbaria** [Nishitbaria/OpenGrame#38]
### Description

**This issue proposes the implementation of a new feature that showcases ‘Top Creators’ in the left sidebar of our platform. The ‘Top Creators’ section will highlight users who have received the most likes and have the highest number of posts and saved posts.**

**Acceptance Criteria:**

- A new section titled ‘Top Creators’ is added to the left sidebar.
- The section dynamically displays users with the highest number of likes, posts, and saved posts.
- The display should update regularly to reflect the most current statistics.
- Ensure the design is responsive and visually consistent with the existing UI.

### Screenshots

![image](https://github.com/Nishitbaria/OpenGrame/assets/85815172/a160c936-c59e-4f3b-aa6f-825192808de7)

Figma Link : [here](https://www.figma.com/file/y7OzDDuGVslwr9rOYDQ7i2/OpenGrame?type=design&node-id=0%3A1&mode=design&t=aMzewIEoN9dd3iFD-1)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Sid-80** [comment]
@Nishitbaria Please assign me this issue!

**Comment by Nishitbaria** [comment]
Hey @Sid-80  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨

**Comment by Sid-80** [comment]
@Nishitbaria shall I limit the number of top creators

**Comment by Nishitbaria** [comment]
> @Nishitbaria shall I limit the number of top creators

Yes You can add up to 10

**Comment by Sid-80** [comment]
@Nishitbaria I have to find highest number of creator with highest likes, posts, and saved posts or any one of them?

**Comment by Nishitbaria** [comment]
> @Nishitbaria I have to find highest number of creator with highest likes, posts, and saved posts or any one of them?

Consider all the parameters

**Comment by Sid-80** [comment]
@Nishitbaria Hey! I was stuck for filtering the post there must be some likeCount, saveCount, postCount on user schema. Any solution ?

**Comment by Sid-80** [comment]
Querying on the size of array is also not possible

**Comment by Sid-80** [comment]
@Nishitbaria  ?

**Comment by Sid-80** [comment]
@Nishitbaria Help required 🥹!

**Comment by Nishitbaria** [comment]
> @Nishitbaria Help required 🥹!

Hey currently my exam are Going on tomorrow is my paper i will connect with you in discord till then please wait or  work on other issue

**Comment by Sid-80** [comment]
@Nishitbaria ?
