### ISSUE TITLE
[Feature] Share Post Functionality

### ISSUE THREAD

**Issue by CoderSwarup** [Nishitbaria/OpenGrame#45]
### Description

Currently, on website lacks the ability for users to share posts with others. Implementing a "Share Post" functionality would greatly enhance the user experience and encourage engagement with our platform.

Features of Share Post Functionality:

- Share Button: Introduce a "Share" button on each post, allowing users to easily share posts they find interesting or relevant.

- Share Dialog: Upon clicking the "Share" button, display a dialog/modal where users can select sharing options, such as sharing on social media platforms, copying the post link, or sending the post via email or messaging apps.

- Share Counter: Optionally, include a share counter to track the number of times a post has been shared, providing social proof and encouraging further engagement.

I want to work on this issue , please assign me this issue 

### Screenshots

![SHARE POST](https://github.com/Nishitbaria/OpenGrame/assets/128630311/651461f5-ec39-43e8-a783-ee831292134e)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by adarsh-jha-dev** [comment]
Hey @CoderSwarup , will it be okay if i work on this issue? I have a similar project of mine too , so it'd help me a lot.

**Comment by CoderSwarup** [comment]
@adarsh-jha-dev Thank you for your interest in working on this issue! I appreciate your enthusiasm.

I was actually excited to tackle this issue myself as part of my ongoing involvement with Appwrite. It's a great chance for me to level up my skills and contribute meaningfully to the project.

However, I'm open to collaborating or exchanging issues if you have others that you're interested in working on. If you have any other issues in mind that you've raised or would like to suggest, I'd be happy to consider them. use sound like 19 year old boys says this or wirte this so use word like that

**Comment by adarsh-jha-dev** [comment]
> @adarsh-jha-dev Thank you for your interest in working on this issue! I appreciate your enthusiasm.
> 
> I was actually excited to tackle this issue myself as part of my ongoing involvement with Appwrite. It's a great chance for me to level up my skills and contribute meaningfully to the project.
> 
> However, I'm open to collaborating or exchanging issues if you have others that you're interested in working on. If you have any other issues in mind that you've raised or would like to suggest, I'd be happy to consider them. use sound like 19 year old boys says this or wirte this so use word like that

no no, it's okay, you continue working on this, i have raised one more issue, and hopefully i will be assigned to that one, so you please continue with this.

**Comment by CoderSwarup** [comment]
@adarsh-jha-dev ok , thanks
