### ISSUE TITLE
[BUG] Error near signup

### ISSUE THREAD

**Issue by Parimalasri13** [Nishitbaria/OpenGrame#48]
### Description

Instead of showing dont have account it is displayed as  "Already have an Account?"

**Comment by Parimalasri13** [comment]
hello @Nishitbaria,can you please assign this task to me and I am a Gssoc24 contributor

**Comment by Nishitbaria** [comment]
> hello @Nishitbaria,can you please assign this task to me and I am a Gssoc24 contributor

Show me Video of that bug
