### ISSUE TITLE
[OTHER] settings page development

### ISSUE THREAD

**Issue by Parimalasri13** [Nishitbaria/OpenGrame#49]
### What would you like to share or ask?

@Nishitbaria can you please assign this task to me and i am a gssoc24  contributor 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
@Parimalasri13 Which kind of feature you are implementing on this page

**Comment by sambitsingha** [comment]
@Nishitbaria Hey I would like to work on this issue. 

For the stratinng phaase , adding the Account Settings like Profile information , email and phone number , password management. The privacy settings - profile visibility , post visibility , activity status and etc. 

I would like to design the the settings page first first, if assigned. :))
