### ISSUE TITLE
[Feature] change Password and Forget Password

### ISSUE THREAD

**Issue by Parimalasri13** [Nishitbaria/OpenGrame#50]
### Description

this features will enhance the user experience @Nishitbaria can you please assign this task to me 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
Can you explain me how you are going implement this feature

**Comment by Parimalasri13** [comment]
@Nishitbaria I will be designing a page and backend connection if a user needs to change his/her password he can go to that particular page and enter his credentials and he can reset the password. 
When it comes to the forgetting password feature if a user unexpectedly forgets his password he/she can use their mail and can reset the password.
