### ISSUE TITLE
[BUG]  Unrestricted Access to website.

### ISSUE THREAD

**Issue by avayyyyyyy** [Nishitbaria/OpenGrame#51]
### Description

Without user authentication, any user can access the home and other pages.

### Screenshots

<img width="1792" alt="Screenshot 2024-05-13 at 1 54 15 PM" src="https://github.com/Nishitbaria/OpenGrame/assets/111121419/0611980f-f863-4514-b7fb-65c9f9a7c5ce">

### Any additional information?

This misconfiguration can increase the risk of unauthorized access to sensitive information and potential security breaches.

I can work on this feature, please assign this issue to me. 

Thank You.

**Comment by Nishitbaria** [comment]
> ### Description
> Without user authentication, any user can access the home and other pages.
> 
> ### Screenshots
> <img alt="Screenshot 2024-05-13 at 1 54 15 PM" width="1792" src="https://private-user-images.githubusercontent.com/111121419/329977746-0611980f-f863-4514-b7fb-65c9f9a7c5ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTkzMjIsIm5iZiI6MTcxNTU5OTAyMiwicGF0aCI6Ii8xMTExMjE0MTkvMzI5OTc3NzQ2LTA2MTE5ODBmLWY4NjMtNDUxNC1iN2ZiLTY1YzlmOWE3YzVjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxMTE3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lM2ViYjZkNmI1NjhjMjRlMjJmMGEwYjg4NWI2NTRjOGE0MTVlY2I3ZGExZTdmM2M2NmNlODg2ZGU4OTIxNjIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8RIkBwZ9uZ68FNo0Y2MBuFRRNAmUk4dUf-jZk-ohC54">
> ### Any additional information?
> This misconfiguration can increase the risk of unauthorized access to sensitive information and potential security breaches.
> 
> I can work on this feature, please assign this issue to me.
> 
> Thank You.
> 
> ### What browser are you seeing the problem on?
> _No response_

Hey, could you show me the exact issue that the website is experiencing in video form?

**Comment by avayyyyyyy** [comment]
Just like Without logging in, I can visit every page of your website even the particular user's page too, which can lead to unauthorized access and can be harmful for all the users.

**Comment by avayyyyyyy** [comment]
please assign this issue to me. @Nishitbaria
