### ISSUE TITLE
Query: Explore page filter/sort button

### ISSUE THREAD

**Issue by AshutoshDash1999** [Nishitbaria/OpenGrame#59]
### What would you like to share or ask?

Hey, do you have any plans for including some options in this filter/sort button?
![image](https://github.com/Nishitbaria/OpenGrame/assets/46455250/883e62cd-4fef-40cb-ac71-fd27520aad40)

Please let me know, I would like to work on it.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
> ### What would you like to share or ask?
> Hey, do you have any plans for including some options in this filter/sort button? ![image](https://private-user-images.githubusercontent.com/46455250/330163931-883e62cd-4fef-40cb-ac71-fd27520aad40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NTE2MTgsIm5iZiI6MTcxNTY1MTMxOCwicGF0aCI6Ii80NjQ1NTI1MC8zMzAxNjM5MzEtODgzZTYyY2QtNGZlZi00MGNiLWFjNzEtZmQyNzUyMGFhZDQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDAxNDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzYzRlNDM2YjZlNWUzMDM5NzY3NDEzNjY3ZTU3YWZiNTFmMzFkOWY1Mzg3NmM1YzBlMzFiYWU5NGVlYWI5YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yT9CLS-L0aDAQQUO-Ag_SAq3bZsKwkQh4IxRgLAHdao)
> 
> Please let me know, I would like to work on it.
> 
> ### Checklist
> * [x]  I have checked the existing issues
> * [x]  I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
> * [x]  I am willing to work on this issue (optional)

Hey @AshutoshDash1999  **Yes We need this Can you start working on it**

**Comment by AshutoshDash1999** [comment]
@Nishitbaria yes I can start. Please let me know the requirements and what you want to show.

Also shouldn't this be under level 3 as this issue includes adding a new functionality and improving one which already exists?

**Comment by Nishitbaria** [comment]
> @Nishitbaria yes I can start. Please let me know the requirements and what you want to show.
> 
> Also, shouldn't this be under level 3 as this issue includes adding a new functionality and improving existing one?

- Based on Most Linked 
- A-z
- z-a 
etc

**Comment by AshutoshDash1999** [comment]
@Nishitbaria can you please assign me this to me

**Comment by AshutoshDash1999** [comment]
@Nishitbaria  Please review this PR: https://github.com/Nishitbaria/OpenGrame/pull/76
