### ISSUE TITLE
[DARK MODE TOGGLE ON AND OFF TO BE ADDED ON HOME PAGE ] 

### ISSUE THREAD

**Issue by samarth29jc** [Nishitbaria/OpenGrame#61]
### Description

not everyone likes dark mode giving dark mode as only option hinders user experience please assign me this issue to add a toggle on home page so user can browse as per his choice of theme .

### Screenshots

![Screenshot 2024-05-14 010524](https://github.com/Nishitbaria/OpenGrame/assets/139863510/f3c1e86a-d7ca-4f41-af81-65c764bc6d8d)

### Checklist

- [x] I have checked the existing issues
- [x] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)

**Comment by samarth29jc** [comment]
@Nishitbaria @Atharva1723 @SpaciousCoder78 @Manav2808

**Comment by Nishitbaria** [comment]
currently, we don't have any navbar @samarth29jc where you add dark and light modes buttons.

**Comment by samarth29jc** [comment]
on the hompage top by manageing the style the user could navigate to homepage to toggle theme

**Comment by Atharva1723** [comment]
> currently, we don't have any navbar @samarth29jc where you add dark and light modes buttons.

Can we design an simple navbar for now ...It would add new issues too :)

**Comment by Atharva1723** [comment]
I would like to collaborate on this if @samarth29jc agrees

**Comment by samarth29jc** [comment]
> > > Currently, we don't have any navbar @samarth29jc where you add dark and light modes buttons.
> > 
> > 
> > Can we design a simple navbar for now ...It would add new issues too :)
> 
> Its will be Great if you are done in same issue I will increase the level 2 to 3 for this issue

I would love !! please assign me this i will make a simple navbar with few functionalities

**Comment by samarth29jc** [comment]
the project seems great also love the weeb culture there

**Comment by Nishitbaria** [comment]
Then I am Assign both of you @Atharva1723 @samarth29jc  You can start working on this issue
