### ISSUE TITLE
[BUG] Multiple Bookmarks Being Added in Saved Posts

### ISSUE THREAD

**Issue by Atharva1723** [Nishitbaria/OpenGrame#63]
### Description

When users bookmark a post, remove the bookmark, and then bookmark the same post again, the post gets added multiple times in the saved posts section. This results in cluttering of saved posts and inconsistency in user experience.

### Screenshots

![Uploading image.png…]()

### Any additional information?

**Steps to Reproduce**
Log in to the social media app.
Navigate to a post.
Bookmark the post.
Go to the saved posts section to verify the bookmarked post is added.
Remove the bookmark from the post.
Bookmark the same post again.
Check the saved posts section.

**Actual Behavior**
The post gets added multiple times in the saved posts section each time it's bookmarked again.

**Expected Behavior**
The post should be added to the saved posts section only once, regardless of how many times it's bookmarked and unbookmarked.

**Comment by Nishitbaria** [comment]
Hey @Atharva1723  I am assigning this issue to you

you can start working on this issue

Happy hacking ✨
