### ISSUE TITLE
BookMark button on HomePage

### ISSUE THREAD

**Issue by venkatasai24** [Nishitbaria/OpenGrame#64]
### Description

As we can see in the below video, the toggle bookmark button is not working properly, it is only changing once, if we try to toggle again, it does not revert :( 
As I'm a GSSOC'24 contributor, I request you to assign this issue to me @Nishitbaria 

### Screenshots

[Screencast from 2024-05-14 10-51-54.webm](https://github.com/Nishitbaria/OpenGrame/assets/103911586/84f4e3e2-b5ec-4bcc-896c-f794eb1cfe78)

### What browser are you seeing the problem on?

Chrome

**Comment by Nishitbaria** [comment]
Hey @venkatasai24  I am assigning this issue to you

you can start working on this issue

Happy hacking ✨
