### ISSUE TITLE
[BUG] Header Component Icon Not Rendering Properly on Edit Post Page

### ISSUE THREAD

**Issue by Atharva1723** [Nishitbaria/OpenGrame#67]
### Description

When navigating to the edit post page and attempting to edit a post, the header component fails to render as expected. The header should display the title "Edit" along with an icon to the left, but neither the title nor the icon is visible. This issue obstructs users' ability to identify the purpose of the page and affects the overall user experience.

### Screenshots

![editpost](https://github.com/Nishitbaria/OpenGrame/assets/87201444/1e93f31b-3989-462e-86f8-2ad06ba94668)

**Comment by avayyyyyyy** [comment]
Hey @Nishitbaria , I can work on this issue please assign this issue to me.
