### ISSUE TITLE
Learn.md

### ISSUE THREAD

**Issue by sanjay-kv** [Nishitbaria/OpenGrame#7]
Learn repos should have a LEARN.md file to teach student how to build your project step by step. You can explain how to build your project with text, code snippets, images, or even short (5 minute) long video lessons. As the maintainer of a Learn repo, the LEARN.md file requires you to think critically about how to explain the building of your project and how to also make it engaging. We don't expect you to be an expert teacher, but we would like you to reflect on how difficult it was to get to your level of knowledge, and then provide friendly guidance to help other students to learn.

Reference: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/Learn.md

**Comment by Gokilp** [comment]
Assign this issue to me under GSSoc'24 so that i can work on it

**Comment by Gokilp** [comment]
Thank you so much

**Comment by Nishitbaria** [comment]
Sure, here's a refined version of your message:

> Thank you so much!

Hello @Gokilp, 

We need to set up the project and here are the steps we need to follow:

1. Create an account on Appwrite.
2. Set up the backend schema and other necessary configurations for this project in your Appwrite account. This project is entirely dependent on Appwrite.
3. Install the Appwrite CLI, log in with your Appwrite credentials, and obtain the API key.

Are you comfortable with these steps? I have an `appwrite.json` file that will assist in setting up the Appwrite project. If you're able to perform the tasks mentioned above, let me know and I'll assign this issue to you.


You have to write all things things in Readme form or make a video 
so other contributor understand how to setup the project

**Comment by Nishitbaria** [comment]
> assign to me im an beginner i will do i need a help asking to you
> 

i think you can work on readme.md you can check out my other project which is also part of Gssoc take reference of that here is the link
 https://github.com/Nishitbaria/Dev-Exchange/blob/main/README.md

make a similar kind of readmd.md  for opengrame

**Comment by Gokilp** [comment]
Thank you so much

**Comment by iamrudhresh** [comment]
Assign this issue to me under GSSoc'24
