### ISSUE TITLE
Add Post In Home Page

### ISSUE THREAD

**Issue by Rohitha-pudu** [Nishitbaria/OpenGrame#71]
Send post in home page will be better accesible 
![image](https://github.com/Nishitbaria/OpenGrame/assets/116823590/e55694bf-0da3-4648-b386-875e22740b56)

**Comment by Rohitha-pudu** [comment]
can i use materialUI @Nishitbaria

**Comment by Nishitbaria** [comment]
> can i use materialUI @Nishitbaria

Hey We are using only Shadcn and Tailwind CSS @Rohitha-pudu 

materialui will clutter all  things

**Comment by Rohitha-pudu** [comment]
ok @Nishitbaria  i will use tailwind
