### ISSUE TITLE
[Feature] Implementing Story UI on Home page 

### ISSUE THREAD

**Issue by CoderSwarup** [Nishitbaria/OpenGrame#74]
### Description

as i see the FIGMA Design file of the Website their is a story section on the home Page That improve the Page ui And application 

I want to work on this ui feature please assign me that

### Screenshots

![Screenshot_2024-05-15-11-08-49-37_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Nishitbaria/OpenGrame/assets/128630311/b81f11f3-9425-4656-bdf7-e9f49afcb533)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
Hey @CoderSwarup  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨

**Comment by Atharva1723** [comment]
So actually there is an issue regarding creating an navbar for the project then how will we position the story section....Can we discuss this matter

**Comment by Nishitbaria** [comment]
> So actually there is an issue regarding creating an navbar for the project then how will we position the story section....Can we discuss this matter

Hey see here you understand 


![IMG_20240516_213212.jpg](https://github.com/Nishitbaria/OpenGrame/assets/85815172/33a2ea04-462d-4a2a-b59b-fe0aafef5683)


Stories are below the navbar

**Comment by CoderSwarup** [comment]
> > So actually there is an issue regarding creating an navbar for the project then how will we position the story section....Can we discuss this matter
> 
> Hey see here you understand
> 
> ![IMG_20240516_213212.jpg](https://private-user-images.githubusercontent.com/85815172/331284763-33a2ea04-462d-4a2a-b59b-fe0aafef5683.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4Nzc0MTQsIm5iZiI6MTcxNTg3NzExNCwicGF0aCI6Ii84NTgxNTE3Mi8zMzEyODQ3NjMtMzNhMmVhMDQtNDYyZC00YTJhLWI1OWItZmUwYWFmZWY1NjgzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE2MzE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MDJmYzc1ZTEyNjllMzExNGU2MjdjYjFlMzhjOTUyZjM2Mjg0ODlkZWVkYmM4MWJjNDJiZmQwOWEyNzYwMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VVPmPBTDKkrp_OCas1kV7S_bKbiLtiWwA87piV4_cF0)
> 
> Stories are below the navbar

Ok so I don't need to change the position of the story section 
So the query is where I create a create story button on the left sidebar or create a navbar component for it

**Comment by Atharva1723** [comment]
> > So actually there is an issue regarding creating an navbar for the project then how will we position the story section....Can we discuss this matter
> 
> Hey see here you understand
> 
> ![IMG_20240516_213212.jpg](https://private-user-images.githubusercontent.com/85815172/331284763-33a2ea04-462d-4a2a-b59b-fe0aafef5683.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzgyOTksIm5iZiI6MTcxNTg3Nzk5OSwicGF0aCI6Ii84NTgxNTE3Mi8zMzEyODQ3NjMtMzNhMmVhMDQtNDYyZC00YTJhLWI1OWItZmUwYWFmZWY1NjgzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE2NDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYmU5NDNlMjMwNWFiM2ExZjkzMjExYjhjMmMyNGRiNjJlMmNmZjVhZWJjODgzOTEzMGU0MzllOWM4YTE4NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rhDBrfBMa4g7cUvi715IZecgLQUmgOmynuO-laVY5-g)
> 
> Stories are below the navbar

yup understood

**Comment by Atharva1723** [comment]
> > > So actually there is an issue regarding creating an navbar for the project then how will we position the story section....Can we discuss this matter
> > 
> > 
> > Hey see here you understand
> > ![IMG_20240516_213212.jpg](https://private-user-images.githubusercontent.com/85815172/331284763-33a2ea04-462d-4a2a-b59b-fe0aafef5683.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4Nzc0MTQsIm5iZiI6MTcxNTg3NzExNCwicGF0aCI6Ii84NTgxNTE3Mi8zMzEyODQ3NjMtMzNhMmVhMDQtNDYyZC00YTJhLWI1OWItZmUwYWFmZWY1NjgzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE2MzE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MDJmYzc1ZTEyNjllMzExNGU2MjdjYjFlMzhjOTUyZjM2Mjg0ODlkZWVkYmM4MWJjNDJiZmQwOWEyNzYwMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VVPmPBTDKkrp_OCas1kV7S_bKbiLtiWwA87piV4_cF0)
> > Stories are below the navbar
> 
> Ok so I don't need to change the position of the story section So the query is where I create a create story button on the left sidebar or create a navbar component for it

no so basically the sidebar stays a different component , we can also add a divider between the sidebar and the main component , we only have to add the story section onto the main component

**Comment by Atharva1723** [comment]
![Uploading divider.png…]()

**Comment by Atharva1723** [comment]
![Uploading divider.png…]()

**Comment by CoderSwarup** [comment]
> > > > So actually there is an issue regarding creating an navbar for the project then how will we position the story section....Can we discuss this matter
> > > 
> > > 
> > > Hey see here you understand
> > > ![IMG_20240516_213212.jpg](https://private-user-images.githubusercontent.com/85815172/331284763-33a2ea04-462d-4a2a-b59b-fe0aafef5683.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4Nzc0MTQsIm5iZiI6MTcxNTg3NzExNCwicGF0aCI6Ii84NTgxNTE3Mi8zMzEyODQ3NjMtMzNhMmVhMDQtNDYyZC00YTJhLWI1OWItZmUwYWFmZWY1NjgzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE2MzE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MDJmYzc1ZTEyNjllMzExNGU2MjdjYjFlMzhjOTUyZjM2Mjg0ODlkZWVkYmM4MWJjNDJiZmQwOWEyNzYwMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VVPmPBTDKkrp_OCas1kV7S_bKbiLtiWwA87piV4_cF0)
> > > Stories are below the navbar
> > 
> > 
> > Ok so I don't need to change the position of the story section So the query is where I create a create story button on the left sidebar or create a navbar component for it
> 
> no so basically the sidebar stays a different component , we can also add a divider between the sidebar and the main component ,So that it will look visually appealing and well organized, we only have to add the story section onto the main component

@Atharva1723  ok so your build a navbar component
