### ISSUE TITLE
[DOCS]  Lack of Implementation Steps for Storage, Databases, Collections, and User Authentication for Appwrite

### ISSUE THREAD

**Issue by Atharva1723** [Nishitbaria/OpenGrame#77]
### Issue Description

The current documentation for Appwrite lacks clear implementation and creation steps for essential features such as storage, databases, collections, and user authentication. Developers integrating Appwrite into their applications need detailed guidance on how to set up and utilize these functionalities effectively.

**Affected Documentation Section(s):**
Storage Management
Database Management
User Authentication

### Proposed Solution (optional)

The documentation should provide comprehensive instructions and examples for implementing storage, databases, collections, and user authentication in Appwrite.

### Checklist

- [X] I have checked the existing [issues](https://github.com/Nishitbaria/OpenGrame/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Atharva1723** [comment]
I am facing issues with authentication while setting up the project locally

**Comment by Nishitbaria** [comment]
> I am facing issues with authentication while setting up the project locally

once my exam is completed I will Create details How to setup Project locally but if you know how to setup you can add that doc 
its will be Great 

Also I have added already added  appwrite.json there you need to just login appwrite using cli and just init the project and deploy the service using appwrite cli

**Comment by Atharva1723** [comment]
> > I am facing issues with authentication while setting up the project locally
> 
> once my exam is completed I will Create details How to setup Project locally but if you know how to setup you can add that doc its will be Great
> 
> Also I have added already added appwrite.json there you need to just login appwrite using cli and just init the project and deploy the service using appwrite cli

Yes i have the connected appwrite with the project, and the requests are going to server and the user is created but not able to authenticate and login
