### ISSUE TITLE
[BUG] Scrollbar in the Signup form and show passoword eye can be also added

### ISSUE THREAD

**Issue by mukulpythondev** [Nishitbaria/OpenGrame#79]
### Description

The signup page layout on OpenGrame currently features a form on the left side and an accompanying image on the right. However, the height of the form on the left side is causing the entire page to display a scrollbar, potentially disrupting the user experience. It's necessary to address this issue by adjusting the form's height or reevaluating the layout to prevent the unnecessary appearance of the scrollbar while maintaining the intended design aesthetic.
The passoword field should have show password icon can also added.

### Screenshots

![page1](https://github.com/Nishitbaria/OpenGrame/assets/134795697/77ad10d1-eca4-42ff-b289-81c5922d59e2)
![page2](https://github.com/Nishitbaria/OpenGrame/assets/134795697/dbe31b79-3203-4093-bf4e-2b098dcc5a96)

### What browser are you seeing the problem on?

Chrome

**Comment by Nishitbaria** [comment]
Hey @mukulpythondev  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨

**Comment by mukulpythondev** [comment]
Thanks  @Nishitbaria  for assigning start working on it raise the pr soon.

**Comment by mukulpythondev** [comment]
@Nishitbaria Please also add the label of the gssoc on this issue.
