### ISSUE TITLE
Profile Page 

### ISSUE THREAD

**Issue by Apurv7777** [Nishitbaria/OpenGrame#80]
### Description

On clicking profile logo on top-right, some blank page appears .

![Screenshot_20240515_223427_Chrome](https://github.com/Nishitbaria/OpenGrame/assets/65327303/8dd3d3c7-ab07-4f1c-ada3-cb2eedda59ec)

### What browser are you seeing the problem on?

Chrome

**Comment by Nishitbaria** [comment]
Show me Video of that @Apurv7777

**Comment by Apurv7777** [comment]
https://github.com/Nishitbaria/OpenGrame/assets/65327303/8b694d95-0130-4804-9b21-b9c697f9e161

**Comment by Apurv7777** [comment]
Also, website takes a bit long time to load.
