### ISSUE TITLE
[OTHER] : Clarify messaging on Login and Signup pages

### ISSUE THREAD

**Issue by Vimall03** [Nishitbaria/OpenGrame#81]
### What would you like to share or ask?

**Issue**
The messaging on the Login and Signup pages is currently inconsistent and potentially confusing for users. Specifically, the text "already have an account ? Login" appears on both pages, and for Signup, it also says "already have an account ? Signup", which might lead to user confusion.

**Steps to Reproduce**
Visit the Login page.
Observe the text near the Signup option.
Visit the Signup page.
Observe the text near the Login option.

**Expected Behavior**
The messaging on both the Login and Signup pages should be clear and consistent, guiding users effectively.

**Proposed Solution**
Clarify the messaging to provide clear instructions for users, ensuring consistency across both pages. For example:

- On the Login page: "Don't have an account? Sign up."

- On the Signup page: "Already have an account? Log in."

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
as please create issue with Issue Template then i will be assign the issue again
