### ISSUE TITLE
[Feature] Mention people in post

### ISSUE THREAD

**Issue by YadlaMani** [Nishitbaria/OpenGrame#84]
### Description

Like other social media apps i think it would be great if we add the tag feature in post section which will increase the website usage more.

### Checklist

- [x] #87
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Nishitbaria** [comment]
Hey @YadlaMani  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨

**Comment by YadlaMani** [comment]
@Nishitbaria can you make it level 2 i should also change the model of the post and have to do significant changes in the code
