### ISSUE TITLE
[BUG] Improve Validation Handling in Create Post Section

### ISSUE THREAD

**Issue by Atharva1723** [Nishitbaria/OpenGrame#90]
### Description

Currently, in the "Create Post" section of our social media app, if a user submits the post form with the caption filled and other fields empty, the application redirects them to the explore page with a generic error message, "Create post failed. Please try again." This behavior is confusing and doesn't provide adequate feedback to users about the missing required fields.

**Steps to Reproduce:**

Navigate to the "Create Post" section of the app.
Fill in the caption field but leave other input fields (such as image, tags, location) empty.
Click the "Create Post" button.
Observe the redirection to the explore page and the generic error message.

### Any additional information?

**Expected Behavior:**
When a user attempts to create a post with missing required fields, the application should:
1 Remain on the "Create Post" page.
2 Display validation messages next to each blank field, indicating that the field is required.
3 Prevent submission of the form until all required fields are filled.

**Proposed Solution:**
Implement client-side validation using JavaScript to check for empty required fields before allowing submission of the post form.
Display inline validation messages next to each empty required field, clearly stating that the field is required for post creation.
If a user attempts to submit the form with missing required fields, prevent the submission and highlight the empty fields to guide the user in completing them.
Only redirect and display a generic error message if there's a server-side error unrelated to validation (e.g., network issues, server failure)

**Comment by Nishitbaria** [comment]
@Atharva1723 are you working on this issue ??
