### ISSUE TITLE
Saved post are not responsive  and count in saved 

### ISSUE THREAD

**Issue by GOURAVSINGH19** [Nishitbaria/OpenGrame#97]
### Description

Saved page is not responsive and we can do one more thing we can add total number of post on saved tag.

### Screenshots

https://github.com/Nishitbaria/OpenGrame/assets/120244528/6ab11445-aa15-4a4f-9964-a9b336b475b0

### What browser are you seeing the problem on?

Chrome

**Comment by Nishitbaria** [comment]
Hey @GOURAVSINGH19  I am assigning this issue to you

you can start working on this issue 

Happy hacking ✨

**Comment by priyankMS** [comment]
hello Guarav 
 Hi, I would like to work on this issue. 
  I can fix this issue and would like to get assigned to it.

**Comment by GOURAVSINGH19** [comment]
Ok You can also work on this issue ...
