### ISSUE TITLE
Add the page of Profile 

### ISSUE THREAD

**Issue by YukiP7** [Nishitbaria/OpenGrame#98]
### Description

##Problem
On clicking the profile icon, it goes blank! I can't see the profile page.

https://github.com/Nishitbaria/OpenGrame/assets/109288720/c6597fd0-eeba-4f72-af3e-f905376a8d2c

##Solution
- I can solve the issue by making a Profile Page 
- Profile page will consist of username & email . 

Please assign this issue to me under Gssoc'24 .

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by YukiP7** [comment]
Hey @Nishitbaria Please assign me this issue under gssoc'24

**Comment by Nishitbaria** [comment]
Hey Profile Page is there : 

![image](https://github.com/Nishitbaria/OpenGrame/assets/85815172/63309fa5-3bf7-427a-8e57-8338cba986da)
