### ISSUE TITLE
[Feature] A clean 404 page

### ISSUE THREAD

**Issue by ritu713** [Nishitbaria/OpenGrame#99]
### Description

As of now, a wrong url search gives user a blank page.
I would like to add a 404/not found page, with a redirect to home page button.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by sambitsingha** [comment]
@ritu713 I haave already done this issue earlier and alos given the PR. So , you should better get along with a new issue :))

**Comment by Nishitbaria** [comment]
Its Duplicate issue
